---
apiVersion: v1
kind: Service
metadata:
  name: s-shah-flask-service
spec:
  type: ClusterIP
  selector:
    app: s-shah-test-flask
  ports:
  - name: s-shah-test-flask
    port: 5000
    targetPort: 5000
