---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-shah-flask-deployment
  labels:
    username: s-shah
    env: test
    app: s-shah-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s-shah-test-flask
  template:
    metadata:
      labels:
        app: s-shah-test-flask
    spec:
      containers:
        - name: s-shah-test-flask
          imagePullPolicy: Always
          image: serenashah/k8s-flask-redis:latest
          command: ['python3', 'app.py']
          ports:
          - name: http
            containerPort: 5000