---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s-shah-data
  labels:
    app: s-shah-test-redis
    username: s-shah
    env: test  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
