---
apiVersion: v1
kind: Service
metadata:
  name: s-shah-service
spec:
  type: ClusterIP
  selector:
    app: s-shah-test-redis
  ports:
  - name: s-shah-test-redis
    port: 6428		
    targetPort: 6379